name: LANTERN_PUBLISH
on:
  push:
    tags:        
      - v1.*.*
  workflow_dispatch: # 手动触发
jobs:
  # This workflow contains a single job called "xxx"
  buildLanternAndPublish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Publish to NPM
      uses: actions/setup-node@v1
      with:
        always-auth: true
        node-version: 12
        registry-url: https://registry.npmjs.com
        scope: '@chuangkit'
    - name: Install dependencies and Build
      run: npm install
    - name: BuildPack
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run build || true
